name: Docker Image CI

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
    steps:
    - name: Login to docker.io
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}
    - uses: actions/checkout@v3
    - name: Set latest tag for the Docker image
      run: docker build . --file Dockerfile --tag $LOGIN/trivy:latest
    - name: Push latest image to docker.io
      run: docker push $LOGIN/trivy:latest
